### ISSUE TITLE
Desarrollar pestaña "Case Setup -> Solver Settings"

### ISSUE THREAD

**Issue by jmarcelogimenez** [jmarcelogimenez/petroSym#1]
Este issue es creado para seguir el desarrollo de la pestaña Case Setup -> Solver Settings. 
Se requiere que el widget agregue:

- una pestaña de nombre PIMPLE o SIMPLE dependiendo del solver a utilizar. 
PIMPLE -> icoFoam, pimpleFoam
SIMPLE -> 
este widget permite setear la cofiguracin particular de estos esquemas de acoplamiento.

- una pestaña por campo a resolver (seleccionandolós del currentFields) y que para cada campo se pueda optar entre tres tipos de resolvedores lineales, a saber:
* GAMG
* gradiente conjugado PCG ("p") o PBiCG ("U", "k", "epsilon", "omega", "T", "nuT")
* smooth solver

**Comment by santichialvo** [comment]
Para gradiente conjugado, los "Preconditioner" pueden ser: 

- PCG: "DIC", "FDIC", "diagonal", "none"
- PBiCG: "DILU", "diagonal", "none"
